services:
  web:
    image: ${IMAGE}               # подставляем из .compose.env
    env_file:
      - .env                      # окружение Next.js
    restart: unless-stopped

  caddy:
    image: caddy:2
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped

volumes:
  caddy-data:
  caddy-config:
