version: "3.9"

services:
  web:
    build:
      context: ../../src       # код репо мы копируем в ~/app/src
      dockerfile: Dockerfile
    env_file:
      - .env                   # лежит рядом (на ВМ), не в репо
    restart: unless-stopped

  caddy:
    image: caddy:2
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped

volumes:
  caddy-data:
  caddy-config:
