services:
  web:
    image: ghcr.io/ivanlakoza-cloud/vitrina-sync/web:latest
    env_file:
      - .env
    restart: unless-stopped

  caddy:
    image: caddy:2
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # для HTTP/3 (нужен открыт UDP:443 в SG)
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped

volumes:
  caddy-data:
  caddy-config:
