name: Deploy to Yandex Cloud (1 VM)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'components/**'
      - 'lib/**'
      - 'public/**'
      - 'next.config.*'
      - 'Dockerfile'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
      - 'package-lock.json'
      - 'deploy/yandex-single-vm/**'
      - 'src/**'

permissions:
  contents: read
  packages: write               # пушим образ в GHCR

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/web

jobs:
  # 1) СБОРКА И ПУШ ОБРАЗА В GHCR
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (with cache)
        uses: docker/build-push-action@v5
        with:
          context: ./src                # если Dockerfile в корне — поставь "." и file: ./Dockerfile
          file: ./src/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # 2) ДЕПЛОЙ НА ВМ
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (только чтобы взять compose/Caddyfile)
        uses: actions/checkout@v4

      - name: Copy compose & Caddyfile to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.YC_VM_HOST }}
          username: ${{ secrets.YC_VM_USER }}
          key: ${{ secrets.YC_VM_SSH_KEY }}
          source: |
            deploy/yandex-single-vm/docker-compose.yml
            deploy/yandex-single-vm/Caddyfile
          target: "~/app/deploy/yandex-single-vm"
          strip_components: 2

      - name: Login to GHCR on VM (нужно, если пакет приватный)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.YC_VM_HOST }}
          username: ${{ secrets.YC_VM_USER }}
          key: ${{ secrets.YC_VM_SSH_KEY }}
          script: |
            echo '${{ secrets.YC_GHCR_TOKEN }}' | docker login ghcr.io -u '${{ github.repository_owner }}' --password-stdin

      - name: Pull & restart on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.YC_VM_HOST }}
          username: ${{ secrets.YC_VM_USER }}
          key: ${{ secrets.YC_VM_SSH_KEY }}
          script: |
            set -e
            DEPLOY_DIR=~/app/deploy/yandex-single-vm
            mkdir -p "$DEPLOY_DIR"

            # .env приложения — создать, если ещё нет
            if [ ! -f "$DEPLOY_DIR/.env" ]; then
              printf '%s\n' \
                'NODE_ENV=production' \
                'PORT=3000' \
                'NEXT_PUBLIC_SITE_URL=https://vitran.ru' \
                'NEXT_TELEMETRY_DISABLED=1' \
                > "$DEPLOY_DIR/.env"
            fi

            # переменная IMAGE для compose-подстановки
            echo "IMAGE=ghcr.io/${{ github.repository }}/web:latest" > "$DEPLOY_DIR/.compose.env"

            cd "$DEPLOY_DIR"
            docker compose --env-file .compose.env pull web
            docker compose --env-file .compose.env up -d --no-build --remove-orphans
            docker image prune -f || true
