      - name: Pull & restart on VM
        uses: appleboy/ssh-action@v1.0.3
        env:
          # user: GHCR_USERNAME или по умолчанию – автор коммита
          GHCR_USER: ${{ secrets.GHCR_USERNAME != '' && secrets.GHCR_USERNAME || github.actor }}
          # token: YC_GHCR_TOKEN или запасной GHCR_TOKEN
          GHCR_TOKEN: ${{ secrets.YC_GHCR_TOKEN != '' && secrets.YC_GHCR_TOKEN || secrets.GHCR_TOKEN }}
        with:
          host: ${{ secrets.YC_VM_HOST }}
          username: ${{ secrets.YC_VM_USER }}
          key: ${{ secrets.YC_VM_SSH_KEY }}
          # передаём env на ВМ
          envs: GHCR_USER,GHCR_TOKEN
          script: |
            set -e
            DEPLOY_DIR=~/app/deploy/yandex-single-vm
            mkdir -p "$DEPLOY_DIR"

            # .env создаём один раз
            if [ ! -f "$DEPLOY_DIR/.env" ]; then
              printf '%s\n' \
                'NODE_ENV=production' \
                'PORT=3000' \
                'NEXT_PUBLIC_SITE_URL=https://vitran.ru' \
                'NEXT_TELEMETRY_DISABLED=1' \
                > "$DEPLOY_DIR/.env"
            fi

            # Проверяем, что креды есть
            if [ -z "$GHCR_USER" ] || [ -z "$GHCR_TOKEN" ]; then
              echo "GHCR creds are missing. Set repo secrets: GHCR_USERNAME and YC_GHCR_TOKEN (or GHCR_TOKEN)." >&2
              exit 1
            fi

            # Логин в GHCR и обновление контейнера
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin

            cd "$DEPLOY_DIR"
            docker compose pull web || true
            docker compose up -d --no-build --remove-orphans
            docker image prune -f || true
