name: Deploy to Yandex Cloud (1 VM)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'components/**'
      - 'lib/**'
      - 'public/**'
      - 'next.config.*'
      - 'Dockerfile'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
      - 'package-lock.json'
      - 'deploy/yandex-single-vm/**'

permissions:
  contents: read
  packages: write   # нужно, чтобы пушить образ в GHCR

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/web
  DEPLOY_DIR: /home/ubuntu/app/deploy/yandex-single-vm

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ВАЖНО: собираем из корня, а не из ./src
      - name: Build & push image (cached)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (только чтобы взять compose/Caddyfile)
        uses: actions/checkout@v4

      # --- Диагностика: увидеть, что реально попало в рабочую папку раннера
      - name: Debug: list files we expect to copy
        run: |
          echo "branch=$GITHUB_REF_NAME  commit=$GITHUB_SHA"
          echo "pwd=$(pwd)"
          ls -lah
          echo "----- deploy dir -----"
          ls -lah deploy || true
          echo "----- yandex-single-vm -----"
          ls -lah deploy/yandex-single-vm || true
          echo "----- files in deploy (max depth 2) -----"
          find deploy -maxdepth 2 -type f -print || true

      # --- Страж: упасть, если нужных файлов нет (чтобы не ловить `tar: empty archive`)
      - name: Guard: ensure deploy files exist
        run: |
          test -f deploy/yandex-single-vm/docker-compose.yml
          test -f deploy/yandex-single-vm/Caddyfile


      - name: Pull & restart on VM
        uses: appleboy/ssh-action@v1.0.3
        env:
          GHCR_USER:  ${{ secrets.GHCR_USER }}   # <- см. шаг 2 ниже
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}  # <- см. шаг 2 ниже
        with:
          host: ${{ secrets.YC_VM_HOST }}
          username: ${{ secrets.YC_VM_USER }}
          key: ${{ secrets.YC_VM_SSH_KEY }}
          script: |
            set -e
            DEPLOY_DIR="$HOME/app/deploy/yandex-single-vm"
            mkdir -p "$DEPLOY_DIR"

            # создаём .env один раз
            if [ ! -f "$DEPLOY_DIR/.env" ]; then
              printf '%s\n' \
                'NODE_ENV=production' \
                'PORT=3000' \
                'NEXT_PUBLIC_SITE_URL=https://vitran.ru' \
                'NEXT_TELEMETRY_DISABLED=1' \
                > "$DEPLOY_DIR/.env"
            fi

            # вход в GHCR, чтобы контейнер "web" мог подтянуть образ
            echo "${GHCR_TOKEN}" | docker login ghcr.io -u "${GHCR_USER}" --password-stdin

            cd "$DEPLOY_DIR"
            docker compose pull web
            docker compose up -d --no-build --remove-orphans
            docker image prune -f || true
